In [1]:
import numpy as np
import cv2

import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

import os

import puzzletools as tools
from puzzlesolving import PuzzlePiece

In [2]:
# create a list of all the images in the folder
# Gets the puzzle piece image
def get_piece_image(path):
    # images are of the format piece#.png
    img = cv2.imread(path)
    return img

piece_dir = '../dataset/pieces-clean'
image_files = os.listdir(piece_dir)
image_files = sorted(image_files, key=lambda x: int(x[5:-4]))

# load all off the images
piece_images = []
for i in tqdm(range(len(image_files))):
    piece_images.append( get_piece_image(os.path.join(piece_dir, image_files[i])) )

piece_contours = []
for i in range(len(piece_images)):
    piece_contours.append(tools.get_contour(piece_images[i]))

  0%|          | 0/1000 [00:00<?, ?it/s]

In [3]:
def test1():
    corners = []
    for i in range(len(piece_contours)):
        corners.append(tools.find_corners(piece_contours[i]))
        
    def get_shortest_edge(corners, contour_len):
        shortest_edge = np.inf
        for i in range(4):
            length = corners[i] - corners[i-1]
            if length < 0:
                length += contour_len
            if length < shortest_edge:
                shortest_edge = length
        return shortest_edge
    def get_longest_edge(corners, contour_len):
        longest_edge = 0
        for i in range(4):
            length = corners[i] - corners[i-1]
            if length < 0:
                length += contour_len
            if length > longest_edge:
                longest_edge = length
        return longest_edge

    # find shortest and longest edges
    short_lengths = np.zeros(len(piece_contours))
    long_lengths = np.zeros(len(piece_contours))
    for i in range(len(corners)):
        short_lengths[i] = get_shortest_edge(corners[i], len(piece_contours[i]))
        long_lengths[i] = get_longest_edge(corners[i], len(piece_contours[i]))

    indices = np.argsort(short_lengths)
    for i in range(10):
        print("Length: {}, Index: {}".format(short_lengths[indices[i]], indices[i]))

    indices = np.argsort(long_lengths)
    for i in range(10):
        print("Length: {}, Index: {}".format(long_lengths[indices[i]], indices[i]))

In [4]:
# test the puzzle piece class
def test2(i = 499):
    
    piece = PuzzlePiece(piece_contours[i])
    plt.plot(piece.normalized_edges[0][:,0], piece.normalized_edges[0][:,1])

In [14]:
pieces = []
for i in tqdm(range(len(piece_contours))):
    pieces.append(PuzzlePiece(piece_contours[i]))

  0%|          | 0/1000 [00:00<?, ?it/s]

In [6]:
def test3():
    from puzzlesolving import Puzzle

    board = Puzzle(pieces, (25, 40))
    print(board.solve_piece(0, 0))

In [16]:
from puzzlesolving import Puzzle
print(pieces[0].edge_types)
board = Puzzle(pieces, (25, 40))
board.get_pocket(0, 0)


['outer', 'flat', 'flat', 'inner']


([None, None, None, None], ['flat', None, None, 'flat'])

In [26]:
board.place_piece(1, 0, 42, 3)

In [27]:
board.solve_piece(1, 1)

(array([[182,   3],
        [200,   3],
        [692,   3],
        [173,   3],
        [426,   1],
        [564,   3],
        [180,   3],
        [704,   1],
        [646,   1],
        [994,   3]]),
 array([ 849.84380898,  958.89608369, 1012.98890586, 1182.33617678,
        1289.85407534, 1300.31082914, 1551.33289492, 1597.11959009,
        1712.85447895, 1832.04770399]))

In [9]:
test3()

(array([[ 3,  1],
       [ 0,  2],
       [ 1,  3],
       [ 2,  0],
       [51,  2],
       [51,  3],
       [52,  0],
       [52,  1],
       [52,  2],
       [52,  3]]), array([ 0.,  0.,  0.,  0., inf, inf, inf, inf, inf, inf]))
